### ISSUE TITLE
Why PHP?

### ISSUE THREAD

**Issue by putra4648** [AdiCahyaSaputra/sistem-antrian#1]
Kenapa gk pake Nodejs aja bang?

**Comment by Octagram82** [comment]
Sayang??>_

**Comment by AdiCahyaSaputra** [comment]
> Kenapa gk pake Nodejs aja bang?

Itu campur sih, php laravel buat core nya, express socket io buat fitur realtime (ganti nomor antrian di display)

**Comment by putra4648** [comment]
Oalah
